spring:
  application:
    name: document-generator
  main:
    web-application-type: none

generator:
  api:
    base-url: http://localhost:8080
    create-endpoint: /api/documents
  documents:
    count: 100
    author: generator
    title-prefix: Generated document
    initiator: generator

logging:
  level:
    root: INFO

